name: Teardown CDK stack

on:
  workflow_dispatch

jobs:
  teardown:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20.11.0

      - name: Teardown CDK stack
        run: |
          npm install
          npm run cdk:destroy